Repository Foundryborne/daggerheart, pull requests merged in 2025-08, with the labels that each got.

#504 [Fix] /dr command
  daggerheart.mjs
Labels: bug

#510 [Bugfix] Fix elements style from features descriptions
  styles/less/global/elements.less
  styles/less/global/inventory-item.less
  styles/less/global/prose-mirror.less
  styles/less/sheets/actors/adversary/sidebar.less
  styles/less/sheets/actors/character/header.less
Labels: bug

#523 [Feature] Add new domains images to use in domain card items from srd compedium
  assets/icons/domains/domain-card/arcana.png
  assets/icons/domains/domain-card/blade.png
  assets/icons/domains/domain-card/bone.png
  assets/icons/domains/domain-card/codex.png
  assets/icons/domains/domain-card/grace.png
  assets/icons/domains/domain-card/midnight.png
  assets/icons/domains/domain-card/sage.png
  assets/icons/domains/domain-card/splendor.png
  assets/icons/domains/domain-card/valor.png
Labels: enhancement

#525 [Fix] Adversary Features To Chat
  module/applications/sheets/api/application-mixin.mjs
  module/applications/ui/chatLog.mjs
  module/documents/item.mjs
  templates/sheets/actors/adversary/features.hbs
  templates/sheets/global/partials/inventory-fieldset-items-V2.hbs
  templates/sheets/global/partials/inventory-item-V2.hbs
  templates/ui/chat/ability-use.hbs
Labels: bug, enhancement

#529 [Feature] Loadout&Domains Homebrew
  daggerheart.mjs
  lang/en.json
  module/applications/settings/appearanceSettings.mjs
  module/applications/sheets/actors/character.mjs
  module/applications/sheets/items/class.mjs
  module/config/settingsConfig.mjs
  module/data/actor/character.mjs
  module/data/item/class.mjs
  module/data/settings/Appearance.mjs
  module/data/settings/Homebrew.mjs
  module/documents/actor.mjs
  module/helpers/utils.mjs
  styles/less/ui/settings/settings.less
  templates/settings/homebrew-settings.hbs
Labels: enhancement

#534 [Feature] ActiveEffects origins
  module/data/action/baseAction.mjs
  module/documents/activeEffect.mjs
  module/documents/chatMessage.mjs
Labels: enhancement

#557 [Feature] 470 - Bone Domain Compendium
  src/packs/domains/domainCard_Bone_Touched_ON5bvnoQBy0SYc9Y.json
  src/packs/domains/domainCard_Boost_VKAHS6eWz28ukcDs.json
  src/packs/domains/domainCard_Brace_QXs4vssSqNGQu5b8.json
  src/packs/domains/domainCard_Breaking_Blow_8UANBgSdhMZ0sqfO.json
  src/packs/domains/domainCard_Cruel_Precision_bap1eCWryPNowbyo.json
  src/packs/domains/domainCard_Deathrun_xFOSn8IVVNizgHFq.json
  src/packs/domains/domainCard_Deft_Maneuvers_dc4rAXlv95srZUct.json
  src/packs/domains/domainCard_Ferocity_jSQsSP61CX4MhSN7.json
  src/packs/domains/domainCard_I_See_It_Coming_Kp6RejHGimnuoBom.json
  src/packs/domains/domainCard_Know_Thy_Enemy_O38MQMhJWdZnXi6b.json
  src/packs/domains/domainCard_On_the_Brink_zbxPl81kbWEegKQN.json
  src/packs/domains/domainCard_Rapid_Riposte_tceJDcCUefrMS2Ov.json
  src/packs/domains/domainCard_Recovery_gsiQFT6q3WOgqerJ.json
  src/packs/domains/domainCard_Redirect_faU0XkJCbar69PiN.json
  src/packs/domains/domainCard_Signature_Move_LWRkhNY968Cu2Zl5.json
  src/packs/domains/domainCard_Splintering_Strike_TYKfM3H9vBXyWiH4.json
  src/packs/domains/domainCard_Strategic_Approach_5b1awkgTmMp3FVrm.json
  src/packs/domains/domainCard_Swift_Step_H6TqCJBaa1eWEQ1z.json
  src/packs/domains/domainCard_Tactician_WChWEH36lUpXAC0K.json
  src/packs/domains/domainCard_Untouchable_9QElncQUDSakuSdR.json
  src/packs/domains/domainCard_Wrangle_9DwSxHoUwl8Kxj3n.json
Labels: enhancement

#558 [Bug] 556 - Character Initial Hope
  module/data/actor/adversary.mjs
  module/data/actor/character.mjs
  module/data/actor/companion.mjs
  module/data/fields/actorField.mjs
Labels: bug

#569 [Feature] 568 - Wizard
  src/packs/classes/class_Wizard_5LwX4m8ziY3F1ZGC.json
  src/packs/classes/feature_Not_This_Time_h3VE0jhcM5xHKBs4.json
  src/packs/classes/feature_Prestidigitation_SG2uw8h5YuwDviCn.json
  src/packs/classes/feature_Strange_Patterns_6YsfFjmCGuFYVhT4.json
  src/packs/classes/folders_Wizard_SwEjiVLbnXT2x9Lz.json
  src/packs/classes/folders_Wizard_utPGR3Z1uORKlNQw.json
  src/packs/classes/loot_Tiny_Elemental_Pet_UUp0YGFj7E4x7Z6Z.json
  src/packs/classes/loot_Untranslated_Book_fhg3NK99tcgYQxdY.json
  src/packs/subclasses/feature_Accomplished_0wCctRupJAv5hTuE.json
  src/packs/subclasses/feature_Adept_v511C6GMShsBblah.json
  src/packs/subclasses/feature_Battlemage_Y9eGMewnFZgPvX0M.json
  src/packs/subclasses/feature_Brilliant_2A0HBDxGc4gEARou.json
  src/packs/subclasses/feature_Conjure_Shield_oirsCnN66GOlK3Fa.json
  src/packs/subclasses/feature_Face_Your_Fear_D3ffFWSXCza4WGcM.json
  src/packs/subclasses/feature_Fueled_by_Fear_hNqLf3zEfKRzSbvq.json
  src/packs/subclasses/feature_Have_No_Fear_8TH6h6a36h09mf6d.json
  src/packs/subclasses/feature_Honed_Expertise_w1BwNKxbQOSizLmZ.json
  src/packs/subclasses/feature_Perfect_Recall_HzPa5U0EQhDfFTqW.json
  src/packs/subclasses/feature_Prepared_YS52ZGdce605wNVT.json
  src/packs/subclasses/feature_Thrive_in_Chaos_1nmFmkNXY6OYyyju.json
  src/packs/subclasses/folders_Wizard_8dyHGlppj08jYLIO.json
  src/packs/subclasses/folders_Wizard_Bb9SLVpYHGBrOB59.json
  src/packs/subclasses/folders_Wizard_IIW7boHWq1QoYwOQ.json
  src/packs/subclasses/folders_Wizard_t8AkyVM60h7WuLOD.json
  src/packs/subclasses/subclass_School_Of_Knowledge_qqQlgCqhOivUFoQn.json
  src/packs/subclasses/subclass_School_Of_War_4y9Ph7RsCIAbkwTk.json
Labels: compendium

#632 [Feature] Style level up application
  module/applications/levelup/levelup.mjs
  styles/less/dialog/index.less
  styles/less/dialog/level-up/footer.less
  styles/less/dialog/level-up/navigation-container.less
  styles/less/dialog/level-up/selections-container.less
  styles/less/dialog/level-up/sheet.less
  styles/less/dialog/level-up/summary-container.less
  styles/less/dialog/level-up/tiers-container.less
  styles/less/global/elements.less
  templates/components/card-preview.hbs
  templates/levelup/tabs/footer.hbs
  templates/levelup/tabs/selections.hbs
  templates/levelup/tabs/summary.hbs
  templates/levelup/tabs/tab-navigation.hbs
Labels: enhancement

#726 Bug/chat roll fixes
  module/applications/sheets/api/application-mixin.mjs
  module/applications/ui/chatLog.mjs
  module/data/action/baseAction.mjs
  module/data/chat-message/adversaryRoll.mjs
  module/data/fields/action/targetField.mjs
  module/data/fields/actionField.mjs
  module/dice/d20Roll.mjs
  module/dice/damageRoll.mjs
  module/dice/dhRoll.mjs
  module/dice/dualityRoll.mjs
  module/documents/chatMessage.mjs
  src/packs/classes/feature_Rally_PydiMnNCKpd44SGS.json
  src/packs/classes/feature_Rally__Level_5__TVeEyqmPPiRa2r3i.json
  styles/less/global/chat.less
  styles/less/ui/chat/chat.less
  templates/dialogs/dice-roll/costSelection.hbs
  templates/ui/chat/chat-message.hbs
  templates/ui/chat/parts/button-part.hbs
  templates/ui/chat/parts/roll-part.hbs
  templates/ui/chat/parts/target-part.hbs
  templates/ui/chat/roll.hbs
Labels: bug, enhancement

#728 Feature/666 experience hope cost
  module/applications/dialogs/d20RollDialog.mjs
  module/applications/sheets/actors/character.mjs
  module/data/action/baseAction.mjs
  module/data/fields/action/costField.mjs
  module/dice/dhRoll.mjs
  templates/dialogs/dice-roll/costSelection.hbs
  templates/sheets/global/partials/inventory-fieldset-items-V2.hbs
Labels: enhancement

#730 [Bugfix] Eemove very far field from variant rules range section
  templates/settings/variant-rules.hbs
Labels: bug

#729 [Bugfix] Fix item list columns and pretier itemBrowser.mjs
  module/applications/ui/itemBrowser.mjs
  styles/less/ui/item-browser/item-browser.less
Labels: bug

#787 [Fix] Levelup Fixes
  module/applications/levelup/characterLevelup.mjs
  module/applications/levelup/companionLevelup.mjs
  module/data/actor/character.mjs
  module/data/item/class.mjs
  module/data/item/subclass.mjs
  module/documents/actor.mjs
  module/helpers/utils.mjs
  templates/sheets/actors/character/header.hbs
Labels: enhancement

#876 [Fix] Hide Item Attachments
  module/applications/sheets/api/item-attachment-sheet.mjs
  module/data/item/weapon.mjs
Labels: bug

#879 [Feature] Companion Independent Levelup
  lang/en.json
  module/applications/levelup/companionLevelup.mjs
  module/applications/sheets/actors/companion.mjs
  module/data/actor/character.mjs
  module/data/actor/companion.mjs
  module/data/levelTier.mjs
  module/data/levelup.mjs
  module/documents/actor.mjs
  styles/less/sheets/actors/companion/header.less
  templates/sheets-settings/companion-settings/details.hbs
  templates/sheets-settings/companion-settings/experiences.hbs
  templates/sheets/actors/companion/details.hbs
  templates/sheets/actors/companion/header.hbs
Labels: enhancement

#887 [Feature] Descriptions enhancements
  lang/en.json
  module/applications/sheets/api/application-mixin.mjs
  module/data/item/domainCard.mjs
  module/data/settings/Appearance.mjs
  styles/less/global/inventory-item.less
  system.json
  templates/settings/appearance-settings.hbs
  templates/sheets/global/partials/inventory-item-V2.hbs
Labels: enhancement

#981 [PR]Add setup script for development
  .env.example
  .gitignore
  README.md
  package.json
  tools/dev-setup.mjs
  tools/run-start.mjs
Labels: enhancement, community pr

#1002 [Community PR] Localize hardcoded text
  lang/en.json
  module/applications/ui/itemBrowser.mjs
  module/config/itemBrowserConfig.mjs
  module/data/fields/action/costField.mjs
  module/data/fields/action/usesField.mjs
  module/helpers/handlebarsHelper.mjs
  templates/sheets/actors/character/header.hbs
  templates/ui/chat/parts/target-part.hbs
  templates/ui/itemBrowser/itemBrowser.hbs
Labels: enhancement, community pr
