Repository Foundryborne/daggerheart, pull requests merged in 2025-07, with the labels that each got.

#225 [Feature] Collapsible Items Description in List View #198
  styles/daggerheart.css
  styles/less/global/elements.less
  templates/sheets/global/partials/inventory-item.hbs
Labels: enhancement, low-priority, maybe

#228 [Feature] 155 - New Adversary Sheet
  lang/en.json
  module/applications/_module.mjs
  module/applications/sheets/actors/adversary.mjs
  module/applications/sheets/actors/character.mjs
  module/applications/sheets/applications/adversary-settings.mjs
  module/config/actionConfig.mjs
  module/config/actorConfig.mjs
  module/config/itemConfig.mjs
  module/data/action/action.mjs
  module/data/actor/adversary.mjs
  styles/daggerheart.css
  styles/daggerheart.less
  styles/less/actors/adversary/actions.less
  styles/less/actors/adversary/header.less
  styles/less/actors/adversary/sheet.less
  styles/less/actors/adversary/sidebar.less
  styles/less/actors/character/sheet.less
  styles/less/actors/character/sidebar.less
  styles/less/applications/adversary-settings/actions.less
  styles/less/applications/adversary-settings/experiences.less
  styles/less/applications/adversary-settings/sheet.less
  styles/less/applications/header.less
  styles/less/global/dialog.less
  styles/less/global/elements.less
  styles/less/global/inventory-fieldset-items.less
  styles/less/global/inventory-item.less
  styles/less/global/prose-mirror.less
  styles/less/global/tab-navigation.less
  templates/sheets/actors/adversary/actions.hbs
  templates/sheets/actors/adversary/effects.hbs
  templates/sheets/actors/adversary/header.hbs
  templates/sheets/actors/adversary/main.hbs
  templates/sheets/actors/adversary/notes.hbs
  templates/sheets/actors/adversary/sidebar.hbs
  templates/sheets/actors/character/sidebar.hbs
  templates/sheets/applications/adversary-settings/actions.hbs
  templates/sheets/applications/adversary-settings/attack.hbs
  templates/sheets/applications/adversary-settings/details.hbs
  templates/sheets/applications/adversary-settings/experiences.hbs
  templates/sheets/applications/adversary-settings/header.hbs
  templates/sheets/global/partials/inventory-fieldset-items.hbs
  templates/sheets/global/partials/inventory-item.hbs
Labels: enhancement

#252 Feature/238 companion sheet template
  lang/en.json
  module/applications/_module.mjs
  module/applications/sheets/actors/companion.mjs
  module/applications/sheets/applications/companion-settings.mjs
  module/applications/sheets/companion.mjs
  module/data/actor/companion.mjs
  module/documents/actor.mjs
  styles/daggerheart.css
  styles/daggerheart.less
  styles/less/actors/companion/details.less
  styles/less/actors/companion/header.less
  styles/less/actors/companion/sheet.less
  styles/less/global/elements.less
  templates/sheets/actors/companion/details.hbs
  templates/sheets/actors/companion/effects.hbs
  templates/sheets/actors/companion/header.hbs
  templates/sheets/applications/companion-settings/attack.hbs
  templates/sheets/applications/companion-settings/details.hbs
  templates/sheets/applications/companion-settings/experiences.hbs
  templates/sheets/applications/companion-settings/header.hbs
  templates/sheets/global/partials/inventory-item.hbs
Labels: enhancement

#267 REFACTOR: move _createSearchFilter from `_onFirstRender` to `_onRender`
  module/applications/sheets/actors/character.mjs
Labels: bug

#272 new style for dialog roll and remove console.log debuggers
  assets/icons/dice/adv/d10.svg
  assets/icons/dice/adv/d12.svg
  assets/icons/dice/adv/d20.svg
  assets/icons/dice/adv/d4.svg
  assets/icons/dice/adv/d6.svg
  assets/icons/dice/adv/d8.svg
  assets/icons/dice/default/d10.svg
  assets/icons/dice/default/d12.svg
  assets/icons/dice/default/d20.svg
  assets/icons/dice/default/d4.svg
  assets/icons/dice/default/d6.svg
  assets/icons/dice/default/d8.svg
  assets/icons/dice/disadv/d10.svg
  assets/icons/dice/disadv/d12.svg
  assets/icons/dice/disadv/d20.svg
  assets/icons/dice/disadv/d4.svg
  assets/icons/dice/disadv/d6.svg
  assets/icons/dice/disadv/d8.svg
  assets/icons/dice/fear/d10.svg
  assets/icons/dice/fear/d12.svg
  assets/icons/dice/fear/d20.svg
  assets/icons/dice/fear/d4.svg
  assets/icons/dice/fear/d6.svg
  assets/icons/dice/fear/d8.svg
  assets/icons/dice/hope/d10.svg
  assets/icons/dice/hope/d12.svg
  assets/icons/dice/hope/d20.svg
  assets/icons/dice/hope/d4.svg
  assets/icons/dice/hope/d6.svg
  assets/icons/dice/hope/d8.svg
  lang/en.json
  module/applications/dialogs/costSelectionDialog.mjs
  module/applications/dialogs/d20RollDialog.mjs
  module/applications/dialogs/damageDialog.mjs
  module/applications/dialogs/damageSelectionDialog.mjs
  module/applications/sheets/actors/adversary.mjs
  module/applications/sheets/actors/character.mjs
  module/data/action/baseAction.mjs
  styles/application.less
  styles/daggerheart.less
  styles/less/dialog/dice-roll/roll-selection.less
  styles/less/utils/colors.less
  styles/less/utils/mixin.less
  templates/dialogs/dice-roll/costSelection.hbs
  templates/dialogs/dice-roll/damageSelection.hbs
  templates/dialogs/dice-roll/header.hbs
  templates/dialogs/dice-roll/rollSelection.hbs
  templates/dialogs/npcRollSelection.hbs
  templates/dialogs/rollSelection.hbs
  tools/create-symlink.mjs
Labels: enhancement

#270 Bug/153 undeploy jquery
  daggerheart.mjs
  module/applications/ui/chatLog.mjs
  module/applications/ux/_module.mjs
  module/applications/ux/contextMenu.mjs
  module/applications/ux/filter-menu.mjs
  module/data/item/base.mjs
  module/helpers/handlebarsHelper.mjs
  templates/characterCreation/tabs/setup.hbs
  templates/levelup/tabs/selections.hbs
  templates/levelup/tabs/summary.hbs
  templates/sheets/actors/companion/tempMain.hbs
Labels: bug

#329 fix firefox problems
  styles/less/sheets/actors/adversary/sheet.less
  styles/less/sheets/actors/adversary/sidebar.less
  styles/less/sheets/actors/character/sheet.less
  styles/less/sheets/actors/character/sidebar.less
  styles/less/sheets/actors/companion/header.less
Labels: bug

#403 [Fixes] typo on a translation for ownershipSelection
  templates/dialogs/ownershipSelection.hbs
Labels: bug

#404 [BUGFIX] - Fix scroll problems in char sheet
  styles/less/sheets/actors/character/effects.less
  styles/less/sheets/actors/character/features.less
  styles/less/sheets/actors/character/inventory.less
  styles/less/sheets/actors/character/loadout.less
  styles/less/sheets/actors/character/sheet.less
  styles/less/sheets/actors/character/sidebar.less
  styles/less/sheets/index.less
  styles/less/utils/mixin.less
  templates/sheets/actors/character/effects.hbs
  templates/sheets/actors/character/sidebar.hbs
  templates/sheets/global/partials/inventory-item-V2.hbs
Labels: bug

#400 [Fix] 397 - Reroll Improvements
  lang/en.json
  module/applications/ui/chatLog.mjs
  module/dice/d20Roll.mjs
  module/dice/dhRoll.mjs
  module/dice/dualityRoll.mjs
  styles/less/ui/chat/chat.less
  templates/ui/chat/adversary-roll.hbs
  templates/ui/chat/duality-roll.hbs
Labels: enhancement

#408 Reduce Action Selection click number & Style Action Type Dialog
  lang/en.json
  module/applications/dialogs/_module.mjs
  module/applications/dialogs/actionSelectionDialog.mjs
  module/applications/sheets-configs/action-config.mjs
  module/config/actionConfig.mjs
  module/data/fields/actionField.mjs
  module/documents/item.mjs
  styles/less/dialog/actions/action-list.less
  styles/less/global/elements.css
  styles/less/global/elements.less
  styles/less/global/inventory-item.less
  templates/actionTypes/actionType.hbs
  templates/actionTypes/effect.hbs
  templates/dialogs/actionSelect.hbs
Labels: enhancement

#440 [Feature] Enhance death roll dialog style
  lang/en.json
  module/applications/dialogs/deathMove.mjs
  module/config/generalConfig.mjs
  module/documents/tooltipManager.mjs
  styles/less/dialog/actions/action-list.less
  styles/less/dialog/death-move/death-move-container.less
  styles/less/dialog/downtime/downtime-container.less
  styles/less/dialog/index.less
  styles/less/utils/colors.less
  templates/dialogs/deathMove.hbs
  templates/ui/tooltip/death-move.hbs
Labels: enhancement

#439 [Feature] ActiveEffect Improvements
  module/applications/hud/tokenHUD.mjs
  module/applications/sheets-configs/activeEffectConfig.mjs
  module/canvas/placeables/token.mjs
  module/documents/activeEffect.mjs
  module/documents/actor.mjs
  templates/sheets/global/partials/inventory-item-V2.hbs
Labels: enhancement

#485 [Fix] Fixed Resources
  daggerheart.mjs
  module/helpers/utils.mjs
  templates/sheets/global/partials/inventory-item-V2.hbs
Labels: bug

#488 [Bugfix] Fix style rules to enrich editor
  styles/less/global/index.less
  styles/less/global/prose-mirror.less
  styles/less/global/tab-description.less
Labels: bug

#489 [Feature] Add domain icon into domain cards
  styles/less/global/item-header.less
  styles/less/utils/colors.less
  templates/sheets/items/domainCard/header.hbs
Labels: enhancement
