Repository Foundryborne/daggerheart, pull requests merged in 2025-09, with the labels that each got.

#1172 [Community PR] Restore margins between paragraphs
  styles/less/global/elements.less
Labels: enhancement, community pr

#1186 Add dice value support to Advesaries and Environments
  module/applications/sheets/actors/adversary.mjs
  module/applications/sheets/actors/environment.mjs
Labels: bug, pr

#1185 Update Powerful Beast for Errata changes
  src/packs/beastforms/beastform_Powerful_Beast_m8BVTuJI1wCvzTcf.json
Labels: bug, typo, pr

#1174 [PR] Fix/filter error item browser config
  module/config/itemBrowserConfig.mjs
Labels: bug

#1171 [PR] Remove Unnecessary Fallen Warlord chatDisplay
  src/packs/adversaries/adversary_Fallen_Warlord__Undefeated_Champion_RXkZTwBRi4dJ3JE5.json
Labels: bug, compendium, community pr

#1176 [Community PR] Fix expanded item summary behavior when re-rendering
  module/applications/sheets/api/application-mixin.mjs
Labels: bug, community pr

#1193 [Community PR] Anchor chat message image crop to top
  styles/less/global/chat.less
Labels: bug, community pr

#1123 [PR] [Feature] Remember the position and size of the compendium browser
  module/applications/ui/itemBrowser.mjs
  module/config/flagsConfig.mjs
Labels: enhancement
